### ISSUE TITLE
디렉토리 구조좀 만들어주세요

### ISSUE THREAD

**Issue by minseolee** [Ho-Ya-Ho/begin-react#1]
보기 힘드네요 ㅇㅇ;

**Comment by Ho-Ya-Ho** [comment]
디렉토리구조 만드는법을 몰라서 포기… 크흠
​
-----Original Message-----
From: "Minseo ***@***.***>
To: ***@***.***>;
Cc: ***@***.***>;
Sent: 2021-11-18 (목) 11:09:53 (GMT+09:00)
Subject: [Ho-Ya-Ho/begin-react] 디렉토리 구조좀 만들어주세요 (Issue #1)

보기 힘드네요 ㅇㅇ;
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
​

**Comment by minseolee** [comment]
https://www.google.com/search?q=react+directory+structure&rlz=1C5CHFA_enKR916KR916&oq=react+directory+structure&aqs=chrome.0.0i512l10.3921j0j7&sourceid=chrome&ie=UTF-8

**Comment by Ho-Ya-Ho** [comment]
이야 이런게 있었네 감사합니다 민서씨 ㄷㄷ
 
-----Original Message-----
